version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - marketnet
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - marketnet

  exchange1:
    image: exchange1
    container_name: exchange1
    ports:
      - "40101:40101"
    networks:
      - marketnet

  exchange2:
    image: exchange2
    container_name: exchange2
    ports:
      - "40102:40102"
    networks:
      - marketnet

  exchange3:  
    image: exchange3
    container_name: exchange3
    ports:
      - "40103:40103"
    networks:
      - marketnet

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    depends_on:
      - db
      - redis
      - exchange1
      - exchange2
      - exchange3

    networks:
      - marketnet

networks:
  marketnet:
    driver: bridge
