services:
  app:
    build:
      context: .
    container_name: marketflow
    env_file: ./.env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      exchange1:
        condition: service_started
      exchange2:
        condition: service_started
      exchange3:
        condition: service_started
    command: ["/app/marketflow"]
    networks: [marketnet]

  postgres:
    image: postgres:16
    container_name: marketflow-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql:z  # ← файл из корня
    networks: [marketnet]


  redis:
    image: redis:7
    container_name: marketflow-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [marketnet]

  exchange1:
    image: exchange1:latest
    container_name: exchange1
    pull_policy: never
    # ports:
    #   - "40101:40101"
    networks: [marketnet]

  exchange2:
    image: exchange2:latest
    container_name: exchange2
    pull_policy: never
    # ports:
    #   - "40102:40102"
    networks: [marketnet]

  exchange3:
    image: exchange3:latest
    container_name: exchange3
    pull_policy: never
    # ports:
    #   - "40103:40103"
    networks: [marketnet]

networks:
  marketnet:
    name: marketnet

volumes:
  pgdata:
